version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - './volumenes/postgres:/var/lib/mysql'

  eureka-server:
    image: eureka-server
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  libros:
    image: libro-service
    build: ./libros
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/libros?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  prestamos:
    image: prestamo-service
    build: ./prestamos
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/prestamos?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=admin
    depends_on:
      - eureka-server
      - mysql

  gateway:
    image: gateway-service
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - libros
      - clientes
      - prestamos